### PR TITLE
NTR - Use InheritanceUpdater trait

### PR DESCRIPTION
**Pull request by keulinho**

### CODE REVIEW

**Comment by almare** [comment]
On the administration the assigned Bundles to a product still not appear for variants.

**Comment by keulinho** [comment]
Hey @almare,

fixed it in https://github.com/shopware/swag-docs-bundle-example/pull/25, but it relies on two fixes needed in the core, so we can't merge it for now.
I will update the docs too.

**Comment by almare** [comment]
Thank you for the fix and the info.

**Comment by keulinho** [comment]
hey @almare,

the upstream fixes were merged, so we were able to merge #25 it should work with the latest master now.
Let me know if you still have trouble.

Kind regards
Jonas

**Pull request merged**
